/* Sachgebiet 5: Unfallverhütungsvorschrift Wach- und Sicherungsdienste (DGUV Vorschrift 23).
   Eigene prüfungsnahe Übungsfragen – keine Original-IHK-Fragen.
   Grundlage: Text der DGUV Vorschrift 23 in der Fassung vom 1. Januar 1997 (abgerufen 04.10.2026). */
SK.fragen("uvv", [
  { u: "allg", d: 1, q: "Wofür gilt die DGUV Vorschrift 23?", o: ["Für Wach- und Sicherungstätigkeiten zum Schutz von Personen und Sachwerten", ["Nur für Geldtransporte", "Geldtransporte sind nur ein Teilbereich."], ["Nur für bewaffnete Wachpersonen", "Sie gilt unabhängig von der Bewaffnung."], ["Für alle Arbeitnehmer in Deutschland", "Sie ist eine Spezialvorschrift für Wach- und Sicherungsdienste."]], e: "§ 1 beschreibt den Geltungsbereich.", r: "§ 1 DGUV Vorschrift 23" },
  { u: "allg", d: 1, q: "An wen richten sich die Bestimmungen der DGUV Vorschrift 23, soweit nichts anderes bestimmt ist?", o: ["An Unternehmer und Versicherte", ["Nur an den Unternehmer", "Auch die Versicherten sind Adressaten."], ["Nur an die Versicherten", "Auch der Unternehmer ist Adressat."], ["An den Auftraggeber", "Der Auftraggeber ist nicht Adressat der UVV."]], e: "§ 2: Die Bestimmungen richten sich an Unternehmer und Versicherte.", r: "§ 2 DGUV Vorschrift 23" },
  { u: "allg", d: 2, q: "Was verlangt § 3 der DGUV Vorschrift 23 zur Eignung?", o: ["Wach- und Sicherungstätigkeiten dürfen nur von Versicherten ausgeführt werden, die die erforderlichen Befähigungen besitzen; über die Befähigungen sind Aufzeichnungen zu führen.", ["Jeder Versicherte muss mindestens 1,80 m groß sein.", "Eine solche Anforderung gibt es nicht."], ["Jeder Versicherte muss einen Waffenschein besitzen.", "Das ist keine allgemeine Eignungsvoraussetzung."], ["Die Eignung wird vom Auftraggeber bescheinigt.", "Verantwortlich ist der Unternehmer."]], e: "Die Versicherten dürfen für die Tätigkeit nicht offensichtlich ungeeignet sein.", r: "§ 3 DGUV Vorschrift 23" },
  { u: "allg", d: 2, q: "Was muss der Unternehmer nach § 4 durch Dienstanweisungen regeln?", o: ["Das Verhalten des Wach- und Sicherungspersonals einschließlich des Weitermeldens von Mängeln und besonderen Gefahren", ["Die Höhe der Gehälter", "Das ist nicht Gegenstand der UVV."], ["Die Urlaubsplanung", "Das ist nicht Gegenstand der UVV."], ["Die Preise gegenüber dem Auftraggeber", "Das ist nicht Gegenstand der UVV."]], e: "Die Dienstanweisung nach der UVV dient der Arbeitssicherheit.", r: "§ 4 Abs. 1 DGUV Vorschrift 23" },
  { u: "allg", t: "mc", d: 2, q: "Welche zwei Pflichten haben die Versicherten nach § 4 Abs. 3?", o: ["Die der Arbeitssicherheit dienenden Maßnahmen unterstützen und die Dienstanweisungen befolgen", "Keine Weisungen des Auftraggebers befolgen, die dem Sicherungsauftrag entgegenstehen", ["Die Dienstanweisungen selbst verfassen", "Das ist Aufgabe des Unternehmers."], ["Jede Weisung des Auftraggebers ausführen", "Weisungen, die dem Sicherungsauftrag entgegenstehen, dürfen nicht befolgt werden."]], e: "Die UVV schützt die Versicherten auch vor sicherheitswidrigen Wünschen des Kunden.", r: "§ 4 Abs. 3 DGUV Vorschrift 23" },
  { u: "allg", d: 2, f: 1, q: "Der Objektleiter des Kunden bittet die Wachperson, während der Nachtschicht die Notausgänge abzuschließen und nebenbei allein auf dem Dach eine defekte Lampe zu wechseln. Wie verhält sie sich richtig?", o: ["Sie befolgt die Weisung nicht, weil sie dem Sicherungsauftrag und der Arbeitssicherheit entgegensteht, und informiert ihren Vorgesetzten.", ["Sie führt alles aus – der Kunde ist König.", "Solche Weisungen dürfen nicht befolgt werden."], ["Sie wechselt nur die Lampe.", "Auch das ist eine gefährliche, nicht vereinbarte Nebentätigkeit."], ["Sie schließt nur die Notausgänge ab.", "Das gefährdet Personen und widerspricht dem Sicherungsauftrag."]], e: "Sicherungsumfang und Nebentätigkeiten müssen schriftlich festgelegt sein (§ 6 Abs. 2). Weisungen des Auftraggebers, die dem Sicherungsauftrag entgegenstehen, sind nicht zu befolgen.", r: "§ 4 Abs. 3, § 6 Abs. 2 DGUV Vorschrift 23" },
  { u: "allg", d: 1, q: "Was gilt nach § 5 für Alkohol und andere berauschende Mittel?", o: ["Genuss und Einnahme sind während der Dienstzeit und für einen angemessenen Zeitraum vor dem Einsatz verboten; bei Dienstantritt muss Nüchternheit gegeben sein.", ["Ein Bier in der Pause ist erlaubt.", "Während der Dienstzeit gilt ein vollständiges Verbot."], ["Das Verbot gilt nur für bewaffnete Wachpersonen.", "Es gilt für alle."], ["Erlaubt ist alles, solange niemand etwas merkt.", "Das Verbot gilt unabhängig von der Entdeckung."]], e: "Die Vorschrift erfasst auch den Zeitraum vor dem Dienst.", r: "§ 5 DGUV Vorschrift 23" },
  { u: "allg", t: "tf", d: 1, a: false, q: "Die Unfallverhütungsvorschrift verbietet Alkohol nur während der Dienstzeit; was davor getrunken wird, ist unerheblich.", e: "Das Verbot gilt auch für einen angemessenen Zeitraum vor dem Einsatz. Bei Dienstantritt muss Nüchternheit gegeben sein.", r: "§ 5 DGUV Vorschrift 23" },
  { u: "allg", t: "tf", d: 2, a: true, q: "Das Wach- und Sicherungspersonal ist anhand der Dienstanweisungen vor Aufnahme der Tätigkeit und darüber hinaus regelmäßig zu unterweisen.", e: "Außerdem ist das sicherheitsgerechte Verhalten bei besonderen Gefahren soweit wie möglich zu üben.", r: "§ 4 Abs. 2 DGUV Vorschrift 23" },
  { u: "allg", t: "fa", d: 2, q: "Welche Pflichten haben die Versicherten nach der DGUV Vorschrift 23? Nenne mindestens vier.", m: "Sie unterstützen die der Arbeitssicherheit dienenden Maßnahmen und befolgen die Dienstanweisungen. Sie befolgen keine Weisungen des Auftraggebers, die dem Sicherungsauftrag entgegenstehen. Sie sind bei Dienstantritt nüchtern und nehmen im Dienst keine berauschenden Mittel. Sie melden festgestellte Gefahren und die dagegen getroffenen Maßnahmen dem Unternehmer. Sie benutzen die zur Verfügung gestellten Ausrüstungen und Hilfsmittel bestimmungsgemäß. Brillenträger sichern die Brille gegen Verlieren oder führen eine Ersatzbrille mit.", c: ["Dienstanweisungen befolgen", "keine entgegenstehenden Weisungen des Auftraggebers", "Nüchternheit", "Gefahren melden", "Ausrüstung bestimmungsgemäß benutzen", "Brille sichern"] },

  { u: "objekt", d: 2, q: "Unter welcher Voraussetzung darf der Unternehmer Wach- und Sicherungsaufgaben übernehmen (§ 6)?", o: ["Wenn vermeidbare Gefahrstellen im Objektbereich beseitigt oder ausreichend abgesichert werden", ["Wenn der Auftraggeber einen Rabatt akzeptiert", "Das ist keine Voraussetzung der UVV."], ["Wenn mindestens zehn Wachpersonen eingesetzt werden", "Eine solche Mindestzahl gibt es nicht."], ["Ohne jede Voraussetzung", "Die UVV stellt Bedingungen."]], e: "Außerdem müssen Sicherungsumfang und -ablauf einschließlich Nebentätigkeiten schriftlich festgelegt werden.", r: "§ 6 DGUV Vorschrift 23" },
  { u: "objekt", d: 2, q: "Was muss der Unternehmer sicherstellen, wenn sich bei Sicherungstätigkeiten besondere Gefahren ergeben können (§ 7)?", o: ["Dass das Wach- und Sicherungspersonal überwacht wird", ["Dass das Personal eine Gefahrenzulage erhält", "Das regelt die UVV nicht."], ["Dass das Objekt geschlossen wird", "Das verlangt die Vorschrift nicht."], ["Dass nur Auszubildende eingesetzt werden", "Das wäre gerade nicht sachgerecht."]], e: "Überwachung kann z. B. durch regelmäßige Meldungen, Personen-Notsignal-Anlagen oder Doppelbesetzung erfolgen.", r: "§ 7 DGUV Vorschrift 23" },
  { u: "objekt", d: 2, q: "Wie oft sind die zu sichernden Objekte nach § 8 auf Gefahren zu prüfen?", o: ["Regelmäßig und bei besonderem Anlass unverzüglich", ["Einmalig bei Vertragsabschluss", "Die Prüfung ist regelmäßig zu wiederholen."], ["Nur auf Wunsch des Auftraggebers", "Der Unternehmer ist unabhängig vom Auftraggeber verpflichtet."], ["Alle zehn Jahre", "Die Prüfung hat regelmäßig zu erfolgen."]], e: "Über die Prüfungen sind Aufzeichnungen zu führen.", r: "§ 8 Abs. 1 DGUV Vorschrift 23" },
  { u: "objekt", d: 2, f: 1, q: "Beim nächtlichen Kontrollgang stellt die Wachperson fest, dass ein Gitterrost über einem Schacht fehlt. Sie sperrt die Stelle provisorisch ab. Was muss sie außerdem tun?", o: ["Die Gefahr und die getroffene Maßnahme dem Unternehmer melden", ["Nichts weiter – die Absperrung genügt", "Die Meldung an den Unternehmer ist vorgeschrieben."], ["Den Schacht selbst zubetonieren", "Das ist nicht ihre Aufgabe."], ["Den Vorfall nur dem nächsten Kollegen erzählen", "Erforderlich ist die Meldung an den Unternehmer."]], e: "§ 8 Abs. 3: Die Versicherten haben festgestellte Gefahren und die dagegen getroffenen Maßnahmen dem Unternehmer zu melden.", r: "§ 8 Abs. 3 DGUV Vorschrift 23" },
  { u: "objekt", d: 2, q: "Was verlangt § 9 zur Objekteinweisung?", o: ["Das Personal ist in das jeweilige Objekt und in die spezifischen Gefahren einzuweisen – und zwar zu den Zeiten, zu denen die Tätigkeit ausgeübt wird.", ["Eine Einweisung per E-Mail genügt.", "Die Einweisung erfolgt im Objekt."], ["Die Einweisung erfolgt immer tagsüber, auch für den Nachtdienst.", "Sie ist zu den Zeiten vorzunehmen, zu denen die Tätigkeit ausgeübt wird."], ["Eine Einweisung ist nur bei bewaffneten Diensten nötig.", "Sie ist für alle Objekte vorgeschrieben."]], e: "Wer nachts arbeitet, muss das Objekt auch unter Nachtbedingungen kennenlernen.", r: "§ 9 Abs. 1 und 2 DGUV Vorschrift 23" },
  { u: "objekt", t: "mc", d: 2, q: "Welche zwei Aussagen zur Überprüfung von Objekten (§ 8) treffen zu?", o: ["Der Unternehmer muss die Prüfung unabhängig von den Pflichten des Auftraggebers sicherstellen.", "Der Unternehmer hat vom Auftraggeber zu verlangen, dass vermeidbare Gefahren beseitigt oder Gefahrstellen abgesichert werden.", ["Für Gefahren im Objekt ist allein der Auftraggeber verantwortlich.", "Der Unternehmer hat eigene Pflichten."], ["Aufzeichnungen über die Prüfungen sind nicht erforderlich.", "Aufzeichnungen sind vorgeschrieben."]], e: "Bis zur Beseitigung muss der Unternehmer die Sicherheit des Personals auf andere Weise gewährleisten.", r: "§ 8 DGUV Vorschrift 23" },
  { u: "objekt", t: "tf", d: 2, a: true, q: "In Objekten, in denen Hunde eingesetzt sind, muss das Personal über das Verhalten bei der Begegnung mit diesen Hunden unterwiesen werden.", e: "Das bestimmt § 9 Abs. 3.", r: "§ 9 Abs. 3 DGUV Vorschrift 23" },
  { u: "objekt", t: "mc", d: 2, q: "Welche zwei Angaben müssen bei Übernahme eines Auftrags schriftlich festgelegt werden (§ 6 Abs. 2)?", o: ["Sicherungsumfang und Sicherungsablauf", "Vorgesehene Nebentätigkeiten", ["Die privaten Telefonnummern der Wachpersonen", "Das verlangt die Vorschrift nicht."], ["Die Lieblingsroute der Wachperson", "Das verlangt die Vorschrift nicht."]], e: "Nicht vereinbarte Nebentätigkeiten können die Sicherheit gefährden.", r: "§ 6 Abs. 2 DGUV Vorschrift 23" },

  { u: "ausr", d: 1, q: "Womit muss bei Dunkelheit eingesetztes Wach- und Sicherungspersonal ausgerüstet sein?", o: ["Mit leistungsfähigen Handleuchten", ["Mit Nachtsichtgeräten", "Vorgeschrieben sind Handleuchten."], ["Mit Signalraketen", "Das ist nicht vorgeschrieben."], ["Mit Schusswaffen", "Das ist nicht vorgeschrieben."]], e: "§ 10 Abs. 4.", r: "§ 10 Abs. 4 DGUV Vorschrift 23" },
  { u: "ausr", d: 2, q: "Wie müssen anlegbare Ausrüstungen und Hilfsmittel beschaffen sein (§ 10 Abs. 2)?", o: ["So, dass die Bewegungsfreiheit, insbesondere die der Hände, nicht mehr als unvermeidbar beeinträchtigt wird", ["Möglichst schwer, um Eindruck zu machen", "Das widerspricht der Vorschrift."], ["Farblich passend zur Polizeiuniform", "Verwechslungen mit der Polizei sind zu vermeiden."], ["So, dass sie die Hände dauerhaft binden", "Die Hände sollen frei bleiben."]], e: "Freie Hände sind wichtig für Eigensicherung und zum Abfangen von Stürzen.", r: "§ 10 Abs. 2 DGUV Vorschrift 23" },
  { u: "ausr", d: 1, q: "Was müssen Brillenträger bei Wach- und Sicherungsaufgaben beachten?", o: ["Die Brille gegen Verlieren sichern oder eine Ersatzbrille mitführen", ["Die Brille im Dienst abnehmen", "Das Sehvermögen muss korrigiert bleiben."], ["Nur Kontaktlinsen tragen", "Das ist nicht vorgeschrieben."], ["Nichts Besonderes", "§ 11 enthält eine ausdrückliche Pflicht."]], e: "§ 11.", r: "§ 11 DGUV Vorschrift 23" },
  { u: "ausr", t: "mc", d: 2, q: "Wofür hat der Unternehmer nach § 10 zu sorgen?", o: ["Dass Einrichtungen, Ausrüstungen und Hilfsmittel in ordnungsgemäßem Zustand sind und das Personal in der Handhabung unterwiesen ist", "Dass der Aufgabe entsprechendes Schuhwerk getragen wird", ["Dass jede Wachperson ein Dienstfahrzeug erhält", "Das verlangt die Vorschrift nicht."], ["Dass Ausrüstung von den Versicherten selbst bezahlt wird", "Das regelt die Vorschrift nicht so."]], e: "Die Versicherten haben die Ausrüstung bestimmungsgemäß zu benutzen (§ 10 Abs. 5).", r: "§ 10 DGUV Vorschrift 23" },
  { u: "ausr", t: "tf", d: 1, a: true, q: "Die Versicherten haben die zur Verfügung gestellten Ausrüstungen und Hilfsmittel bestimmungsgemäß zu benutzen.", e: "§ 10 Abs. 5.", r: "§ 10 Abs. 5 DGUV Vorschrift 23" },

  { u: "hund", d: 2, q: "Welche Hunde dürfen als Diensthunde eingesetzt werden?", o: ["Nur geprüfte Hunde mit Hundeführern", ["Jeder Hund, der bellt", "Das genügt nicht."], ["Private Hunde der Wachpersonen ohne Prüfung", "Als Diensthunde sind nur geprüfte Hunde zulässig."], ["Nur Hunde über 40 kg", "Ein Gewicht ist nicht vorgeschrieben."]], e: "Ungeprüfte Hunde dürfen nur zu Wahrnehmungs- und Meldeaufgaben eingesetzt werden, wenn der Führer den Hund unter Kontrolle hat.", r: "§ 12 DGUV Vorschrift 23" },
  { u: "hund", d: 2, q: "Welche Hunde dürfen nach § 12 nicht eingesetzt werden?", o: ["Hunde, die für die Aufgabe ungeeignet sind, zur Bösartigkeit neigen oder deren Leistungsstand nicht mehr gegeben ist", ["Hunde mit kurzem Fell", "Das ist kein Ausschlussgrund."], ["Hunde, die älter als drei Jahre sind", "Das ist kein Ausschlussgrund."], ["Hunde, die gut gehorchen", "Gehorsam ist gerade erwünscht."]], e: "Maßgeblich ist, ob der Hund dadurch Personen gefährden kann.", r: "§ 12 Abs. 1 DGUV Vorschrift 23" },
  { u: "hund", d: 3, q: "Wie hat die Übernahme und Abgabe eines Diensthundes zu erfolgen (§ 16)?", o: ["Im Zwinger bei geschlossener Tür; eine Übergabe von Person zu Person ist nicht erlaubt.", ["Von Hand zu Hand auf dem Parkplatz", "Die Übergabe von Person zu Person ist ausdrücklich nicht erlaubt."], ["Durch Anbinden am Dienstfahrzeug", "Das sieht die Vorschrift nicht vor."], ["Freilaufend auf dem Gelände", "Das ist nicht zulässig."]], e: "Bei zulässiger Anbindehaltung kann die Übernahme auch an den entsprechenden Einrichtungen erfolgen.", r: "§ 16 Abs. 1 DGUV Vorschrift 23" },
  { u: "hund", t: "mc", d: 3, q: "Welche zwei Regeln gelten für die Hundeführung (§ 16)?", o: ["Die Führleine darf nicht am Körper des Hundeführers oder am Fahrrad befestigt werden.", "Bei Begegnung mit Dritten ist der angeleinte Hund an der kurzen Leine so zu führen, dass er Dritte nicht erreichen kann.", ["Hunde werden grundsätzlich ohne Leine geführt.", "Ohne Leine nur dort, wo keine Begegnung mit Dritten zu erwarten ist."], ["Jeder Hundeführer verwendet seine eigenen Kommandos.", "Bei mehreren Hundeführern ist eine einheitliche Kommandosprache festzulegen."]], e: "Die Regeln schützen Hundeführer und Dritte.", r: "§ 16 DGUV Vorschrift 23" },
  { u: "hund", t: "tf", d: 2, a: true, q: "Belegte Hundezwinger dürfen nur von Hundeführern oder vom Unternehmer beauftragten Personen betreten werden, die mit dem jeweiligen Hund vertraut sind.", e: "§ 13 Abs. 3. An den Zwingern ist auf das Zutrittsverbot hinzuweisen.", r: "§ 13 DGUV Vorschrift 23" },
  { u: "hund", d: 2, q: "Wer darf als Hundeführer eingesetzt werden (§ 15)?", o: ["Versicherte, die entsprechend unterwiesen sind und dem Unternehmer ihre Befähigung nachgewiesen haben", ["Jeder, der einen Hund besitzt", "Erforderlich sind Unterweisung und Befähigungsnachweis."], ["Nur Tierärzte", "Das verlangt die Vorschrift nicht."], ["Nur Personen mit Waffenschein", "Das verlangt die Vorschrift nicht."]], e: "Die Befähigung ist regelmäßig nachzuweisen.", r: "§ 15 DGUV Vorschrift 23" },

  { u: "waffe", d: 2, q: "Wann darf das Wach- und Sicherungspersonal nach § 18 mit Schusswaffen ausgerüstet werden?", o: ["Nur wenn der Unternehmer dies ausdrücklich anordnet und die Versicherten zuverlässig, geeignet, sachkundig und an der Waffe ausgebildet sind", ["Immer bei Nachtdiensten", "Die Tageszeit ist kein Kriterium."], ["Wenn die Wachperson es wünscht", "Erforderlich ist die ausdrückliche Anordnung des Unternehmers."], ["Wenn der Auftraggeber die Kosten trägt", "Das ist kein Kriterium."]], e: "Zusätzlich sind die waffenrechtlichen Bestimmungen zu beachten.", r: "§ 18 Abs. 1 DGUV Vorschrift 23" },
  { u: "waffe", d: 2, q: "Was verlangt § 18 Abs. 2 von Trägern von Schusswaffen?", o: ["Regelmäßige Teilnahme an Schießübungen und Nachweis von Schießfertigkeit und Sachkunde", ["Einmalige Einweisung bei der Einstellung", "Die Übungen müssen regelmäßig stattfinden."], ["Tägliches Probeschießen im Objekt", "Schießübungen finden auf zugelassenen Schießständen statt."], ["Keine besonderen Nachweise", "Nachweise sind vorgeschrieben."]], e: "Über Schießübungen, Schießfertigkeit und Sachkundestand sind Aufzeichnungen zu führen.", r: "§ 18 Abs. 2 und 4 DGUV Vorschrift 23" },
  { u: "waffe", d: 2, q: "Wie müssen Schusswaffen im Dienst geführt werden (§ 20)?", o: ["In geeigneten Trageeinrichtungen, die ein Abgleiten oder Herausfallen verhindern", ["Lose in der Jackentasche", "Das ist nicht zulässig."], ["In der Hand", "Die Waffe ist in einer Trageeinrichtung zu führen."], ["Im Rucksack zwischen dem Proviant", "Das ist keine geeignete Trageeinrichtung."]], e: "Munition darf nicht lose mitgeführt werden.", r: "§ 20 Abs. 1 und 2 DGUV Vorschrift 23" },
  { u: "waffe", t: "mc", d: 2, q: "Welche zwei Regeln gelten nach der UVV für die Aufbewahrung von Schusswaffen und Munition (§ 22)?", o: ["Aufbewahrung in verschlossenen Stahlblechschränken mit Sicherheitsschloss oder entsprechend sicheren Einrichtungen", "Schusswaffen dürfen nur im entladenen Zustand aufbewahrt werden", ["Waffen und Munition liegen griffbereit zusammen auf dem Schreibtisch", "Das ist unzulässig."], ["Die Waffe bleibt geladen, damit sie schneller einsatzbereit ist", "Sie ist entladen aufzubewahren."]], e: "Die Einrichtung muss eine getrennte Unterbringung von Waffen und Munition ermöglichen.", r: "§ 22 DGUV Vorschrift 23" },
  { u: "waffe", t: "tf", d: 2, a: true, q: "Schusswaffen müssen mindestens einmal jährlich durch Sachkundige auf ihre Handhabungssicherheit geprüft werden.", e: "§ 19 Abs. 2: bei Verdacht auf Mängel, mindestens jedoch einmal jährlich.", r: "§ 19 Abs. 2 DGUV Vorschrift 23" },

  { u: "geld", d: 2, q: "Welche Personen darf der Unternehmer für Geldtransporte einsetzen (§ 24)?", o: ["Personen, die mindestens 18 Jahre alt, persönlich zuverlässig und geeignet sowie für diese Aufgabe besonders ausgebildet und eingewiesen sind", ["Jede Aushilfe ab 16 Jahren", "Das Mindestalter beträgt 18 Jahre."], ["Nur ehemalige Polizeibeamte", "Das verlangt die Vorschrift nicht."], ["Nur Personen mit Lkw-Führerschein", "Das verlangt die Vorschrift nicht."]], e: "§ 24.", r: "§ 24 DGUV Vorschrift 23" },
  { u: "geld", d: 2, q: "Wie viele Personen müssen einen Geldtransport durch Boten in öffentlich zugänglichen Bereichen grundsätzlich durchführen (§ 25)?", o: ["Mindestens zwei, von denen eine die Sicherung übernimmt", ["Eine", "Grundsätzlich sind mindestens zwei Personen erforderlich."], ["Mindestens vier", "Vorgeschrieben sind mindestens zwei."], ["Es gibt keine Vorgabe", "§ 25 enthält eine klare Vorgabe."]], e: "Das gilt auch für die Wegstrecke zwischen Transportfahrzeug und Übergabe- oder Übernahmestelle.", r: "§ 25 Abs. 1 DGUV Vorschrift 23" },
  { u: "geld", t: "mc", d: 3, q: "In welchen zwei Fällen darf vom Zwei-Personen-Grundsatz beim Botentransport abgewichen werden (§ 25 Abs. 2)?", o: ["Der Transport ist nicht als Geldtransport erkennbar.", "Es wird ausschließlich Hartgeld transportiert und dies ist für Außenstehende erkennbar.", ["Der Bote ist besonders kräftig.", "Das ist kein Ausnahmegrund."], ["Der Transport findet am Vormittag statt.", "Die Tageszeit ist kein Ausnahmegrund."]], e: "Weitere Ausnahmen: Das Geld wird unauffällig in der bürgerlichen Kleidung getragen oder deutlich erkennbare technische Ausrüstung verringert den Anreiz zu Überfällen nachhaltig.", r: "§ 25 Abs. 2 DGUV Vorschrift 23" },
  { u: "geld", t: "tf", d: 2, a: false, q: "Geldtransportbehältnisse dürfen mit dem Boten fest verbunden sein, z. B. durch eine Kette am Handgelenk.", e: "§ 25 Abs. 3: Sie dürfen mit Boten nicht fest verbunden sein – sonst wäre der Bote bei einem Überfall besonders gefährdet.", r: "§ 25 Abs. 3 DGUV Vorschrift 23" },

  { u: "v1", d: 2, q: "Wie oft sind Versicherte nach der DGUV Vorschrift 1 mindestens zu unterweisen?", o: ["Mindestens einmal jährlich", ["Einmal bei der Einstellung genügt", "Die Unterweisung ist zu wiederholen."], ["Alle fünf Jahre", "Die Mindestfrist ist ein Jahr."], ["Nur nach einem Unfall", "Sie hat vorbeugend zu erfolgen."]], e: "§ 4 Abs. 1 DGUV Vorschrift 1: Die Unterweisung muss erforderlichenfalls wiederholt werden, mindestens aber einmal jährlich erfolgen; sie muss dokumentiert werden.", r: "§ 4 Abs. 1 DGUV Vorschrift 1" },
  { u: "v1", d: 2, q: "Wer trägt die Beiträge zur gesetzlichen Unfallversicherung?", o: ["Allein der Unternehmer", ["Arbeitgeber und Arbeitnehmer je zur Hälfte", "Das gilt für andere Zweige der Sozialversicherung."], ["Allein der Arbeitnehmer", "Die Beiträge trägt der Unternehmer."], ["Der Auftraggeber des Sicherheitsunternehmens", "Er ist nicht beitragspflichtig."]], e: "§ 150 Abs. 1 SGB VII: Beitragspflichtig sind die Unternehmer. Träger sind die Berufsgenossenschaften und Unfallkassen.", r: "§ 150 SGB VII" },
  { u: "v1", t: "mc", d: 2, q: "Welche zwei Ereignisse sind Versicherungsfälle der gesetzlichen Unfallversicherung?", o: ["Arbeitsunfall", "Unfall auf dem unmittelbaren Weg zur Arbeit (Wegeunfall)", ["Erkältung im Urlaub", "Sie steht nicht im Zusammenhang mit der versicherten Tätigkeit."], ["Sportverletzung in der Freizeit", "Sie steht nicht im Zusammenhang mit der versicherten Tätigkeit."]], e: "§ 7 SGB VII: Versicherungsfälle sind Arbeitsunfälle und Berufskrankheiten. Nach § 8 Abs. 2 SGB VII gehört auch der unmittelbare Weg nach und von dem Ort der Tätigkeit zur versicherten Tätigkeit.", r: "§§ 7, 8 SGB VII" },
  { u: "v1", t: "fa", d: 2, q: "Welche Grundpflichten hat der Unternehmer nach der DGUV Vorschrift 1, und wie müssen Versicherte mitwirken?", m: "Der Unternehmer hat die erforderlichen Maßnahmen zur Verhütung von Arbeitsunfällen, Berufskrankheiten und arbeitsbedingten Gesundheitsgefahren sowie für eine wirksame Erste Hilfe zu treffen. Er unterweist die Versicherten vor Aufnahme der Tätigkeit und danach mindestens einmal jährlich und dokumentiert dies. Er macht die Vorschriften zugänglich und stellt Ersthelfer und Erste-Hilfe-Material bereit. Die Versicherten unterstützen die Maßnahmen, befolgen Weisungen, benutzen Einrichtungen bestimmungsgemäß, melden Mängel und Gefahren unverzüglich und versetzen sich nicht durch Alkohol oder andere Mittel in einen Zustand, in dem sie sich oder andere gefährden.", c: ["Unfallverhütung und Erste Hilfe organisieren", "Unterweisung mindestens jährlich", "Vorschriften zugänglich machen", "Versicherte: unterstützen, Weisungen befolgen", "Mängel melden", "keine Selbstgefährdung durch Alkohol"] },
  { u: "allg", t: "zu", d: 2, q: "Ordne jeder Vorschrift der DGUV Vorschrift 23 ihren Gegenstand zu.", p: [["§ 3", "Eignung"], ["§ 5", "Verbot berauschender Mittel"], ["§ 9", "Objekteinweisung"], ["§ 11", "Brillenträger"]], e: "Die Paragrafen 2 bis 11 enthalten die gemeinsamen Bestimmungen für alle Wach- und Sicherungstätigkeiten.", r: "DGUV Vorschrift 23" },
  { u: "waffe", t: "mc", d: 2, q: "Welche zwei Regeln gelten nach § 21 für die Übergabe von Schusswaffen?", o: ["Schusswaffen dürfen nur in entladenem Zustand übergeben werden.", "Der Übernehmende überzeugt sich sofort vom Ladezustand und kontrolliert die Waffe auf augenfällige Mängel.", ["Die Waffe wird durchgeladen übergeben.", "Sie ist entladen zu übergeben."], ["Bei festgestellten Mängeln wird die Waffe vorsichtig weiter geführt.", "Bei Mängeln darf die Waffe nicht geführt werden."]], e: "Laden und Entladen erfolgen an sicherem Ort mit Richtung auf eine geeignete Kugelfangeinrichtung.", r: "§ 21 DGUV Vorschrift 23" },
  { u: "geld", t: "mc", d: 3, q: "Welche zwei Regeln gelten für Geldtransportfahrzeuge beim Be- und Entladen in öffentlich zugänglichen Bereichen (§ 26)?", o: ["Das Fahrzeug muss ständig besetzt bleiben.", "Die Türen des besetzten Fahrzeugteils müssen verriegelt sein.", ["Der Motor muss ausgebaut werden.", "Das verlangt die Vorschrift nicht."], ["Alle Türen bleiben geöffnet, damit es schneller geht.", "Die Türen des besetzten Teils sind zu verriegeln."]], e: "Überfälle sind unverzüglich über Funk zu melden.", r: "§ 26 Abs. 5 DGUV Vorschrift 23" },
  { u: "hund", t: "mc", d: 2, q: "Welche zwei Aussagen zu Hundezwingern (§ 13) treffen zu?", o: ["An den Zwingern ist auf das Zutrittsverbot für Unbefugte hinzuweisen.", "Säuberung und Instandhaltung dürfen nur erfolgen, wenn der Zwinger nicht mit einem Hund belegt ist.", ["Mehrere Hunde werden grundsätzlich gemeinsam gehalten.", "Die Zwinger müssen eine Einzelhaltung ermöglichen."], ["Belegte Zwinger bleiben unverschlossen.", "Belegte Zwinger müssen abgeschlossen sein, wenn Entweichen oder Zutritt nicht anders verhindert ist."]], e: "§ 13 regelt Beschaffenheit, Kennzeichnung und Betreten der Zwinger.", r: "§ 13 DGUV Vorschrift 23" }
]);
